services:
  flask:
    build: ./backend
    restart: always

  redis:
    image: redis:alpine3.17
    depends_on:
      - flask
    restart: always

  nginx:
    build: ./nginx
    restart: always
    depends_on:
      - flask
